### ISSUE TITLE
Build Error and Warning while building ACLJ

### ISSUE THREAD

**Issue by Long5hot** [Nishank-25/aclj#1]
While doing `make build` following warnings and errors shows up.

~/academia/aclj master ❯ make build

clang++ main.cpp lex.cpp -Wall --std=c++17 -g  -o aclj

main.cpp:35:21: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                     ^

main.cpp:35:26: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                          ^

main.cpp:35:32: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                                ^
main.cpp:35:38: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                                      ^
main.cpp:35:44: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                                            ^
main.cpp:35:60: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                                                            ^
main.cpp:35:78: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
   35 | char *tok_str[] = { "+", "-" , "*" , "/" , "int literal" , "float literal" , "unknown token"};
      |                                                                              ^
7 warnings generated.
In file included from lex.cpp:1:
./lex.h:26:8: error: unknown type name 'size_t'; did you mean 'std::size_t'?
   26 | extern size_t curr_pos;
      |        ^~~~~~
      |        std::size_t
/usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11/bits/c++config.h:280:26: note: 'std::size_t' declared here
  280 |   typedef __SIZE_TYPE__         size_t;
      |                                 ^
1 error generated.
make: *** [Makefile:2: build] Error 1

**Comment by Nishank-25** [comment]
Hi @Long5hot Thanks for poking around. I appreciate the efforts. As of now I am not taking in any PR's. I was going to fix this anyways.
